name: Docker image tomcatCI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: Login a Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME }}
        password: ${{secrets.DOCKERHUB_TOKEN }}
    -
      name: Establecer Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Construir y subir
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{secrets.DOCKERHUB_USERNAME }}/tomcatci:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/tomcatci:${{ github.sha }}
          